apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:5.7  # Replace with your actual database image
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: example  # Replace with actual key name
          ports:
            - containerPort: 3306
